### PR TITLE
Add 'client' option to support rendering mobile client app when accessing applicaton from mobile

### PR DESCRIPTION
**Pull request by anilmaurya**
Problem: 
I have two ember client application, one for mobile and one for desktop. Whenever user access my domain url ('http://followme.co') then according to device of user I will render my application.
For mobile device , mobile client is rendered and vice versa.

Solution:
I added extra field 'client' when creating new app. This field can be 'web' or 'mobile' . Default is 'web'.
Now, I can create two application with same name but with different client type. 

I updated BestsController to check for user-agent and find app accordingly

### CODE REVIEW

**Comment by ryanto** [comment]
Thanks for the PR. Do you mind outlining what problem this is solving so we can better understand. Thanks!

**Comment by anilmaurya** [comment]
@ryanto I updated description of pull request, Let me know if problem is not clear.

**Comment by ryanto** [comment]
Thanks again for taking the time to write this PR. I think this feature might be out of scope for this project. It sounds like what you really have are two different apps, one for mobile and one for desktop. If you want to serve these apps from the same domain I'd recommend using a [Rails routing constraint](http://guides.rubyonrails.org/routing.html#advanced-constraints) to have mobile clients use the mobile front end builds app and desktop for everything else.

If you have any questions about setting this up I'm happy help you.

**Comment by anilmaurya** [comment]
@ryanto I am not sure how to use Rails routing constraint for maintaining two apps with front_end_builds. Some code example will help me . Thank you

**Comment by anilmaurya** [comment]
This pull request is no longer valid, closing it.

**Pull request closed without merging**
