### PR TITLE
Simplify handling of params

### PR DESCRIPTION
**Pull request by nickcoyne**
Replace the version specific methods with something that will probably require less maintenance. And works for Rails 5.

### CODE REVIEW

**Comment by nickcoyne** [comment]
Builds are failing for Ruby 1.9.3 and 2.2.0. Looks like it may be gem dependency issues.

**Comment by samselikoff** [comment]
@ryanto I don't have commit access here

**Comment by jhirbour** [comment]
@samselikoff or @ryanto can you add me or @danbernier as a owner on [RubyGems](https://rubygems.org/gems/front_end_builds) so we can push new versions of this gem up?

**Comment by ryanto** [comment]
Of course! I need your rubygems emails. I tried using your hirbour.org email, but it said user not found.

**Comment by jhirbour** [comment]
@ryanto just emailed you.

**Comment by ryanto** [comment]
Perfect, you're all set!

**Comment by samselikoff** [comment]
Just as an FYI – on my open-source repos I've started wiring up Travis to be able to publish new versions of our libs (npm, ruby gems). This way, we don't need to manage two sets of permissions. Anyone who has access to the Github repo can release/publish (since Travis is the one releasing).

Wanted to mention this because I really like the pattern and could help in the future.

**Comment by nickcoyne** [comment]
@jhirbour my last commit on this PR removed support for Rails < 5.0. Are you ok with that? I could probably do some more tidying up around that too.

**Comment by jhirbour** [comment]
@nickcoyne I'm discussing internally. I'll get back to you.

**Comment by alexdean** [comment]
@nickcoyne i need to update a FEB-using rails app to rails 5, & i'd like to get this PR merged & tagged & released. are you using this code currently? (tests are passing in travis, but not sure if that's sufficient or not.)

looks like the travis build matrix needs some cleanup (stop testing on rails versions < 5, probably update the set of rubies being tested against), and need some changelog notes. i'm happy to take that.

**Comment by nickcoyne** [comment]
@alexdean yes this code is currently in use on ed.ted.com (Rails 5.1)

```
gem 'front_end_builds',
    git: 'https://github.com/nickcoyne/front_end_builds.git',
    branch: 'simplify-rails-version-param-handling'
```

**Comment by jozefvaclavik** [comment]
I'm also running this branch on Rails 5.2. All good.

**Comment by jhirbour** [comment]
I've created [this PR](https://github.com/tedconf/front_end_builds/pull/84) to incorporate Nick's changes into master. My PR also contains fixes for OpenSSL V2 which is used in Ruby 2.4 and greater.

**Pull request merged**
